FCH-274: Update config normalised with the normalized value
openeuropa/oe_newsroom pull request #4
Opened 2022-06-21 13:05 UTC by piotrsmykaj

2022-06-21 16:45 UTC, brummbar requested changes
Works good, just 1 remark.

2022-06-21 16:45 UTC, brummbar commented on oe_newsroom.post_update.php
> +function oe_newsroom_post_update_10001(&$sandbox) {
```suggestion
function oe_newsroom_post_update_00001(&$sandbox) {
```

2022-06-22 13:05 UTC, brummbar approved these changes

2022-06-22 13:05 UTC, upchuk approved these changes
blind

2022-06-22 13:06 UTC, merged